spring:
  logging:
    level:
      root: ERROR
      org.hibernate.SQL: ERROR
      org.hibernate.type.descriptor.sql.BasicBinder: ERROR
  datasource:
    url: jdbc:mysql://localhost:3306/assignment8a?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  spring:
  kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: gid
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    key-serializer: org.springframework.kafka.support.serializer
    value-serializer: org.springframework.kafka.support.serializer
    properties:
      spring.json.trusted.packages: kafka


